
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: group-id-oing
      auto-offset-reset: earliest
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.apache.kafka.common.serialization.JsonDeserializer
      # JSON 데이터 JsonDeserializer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kafka?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: kafka-test
    password: dkssud123#
    hikari:
      maximum-pool-size: 40
      max-lifetime: 42000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  config: classpath:logback-spring.xml
server:
  port: 8088

